name: Deploy
on:
  workflow_run:
    workflows: [Format, Build]
    types: [completed]
    pull_request:
      branches:
        - main
  push:
    branches:
      - main

jobs:
  on-success:
    runs-on: ubuntu-latest
    name: Deploy

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jackv"
          entrypoint: "main.ts"
          root: "."
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
