name: Format
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - main
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check format
        run: "deno fmt --check"
